extends: base.yaml

backends:
  - namespace: library/.*
    backend:
      registry_tag:
        address: index.docker.io
        security:
          basic:
            username: ""
            password: ""
  - namespace: .*
    backend:
      testfs:
        addr: ${HERD_HOST_IP}:14000
        root: tags
        name_path: docker_tag

cluster:
  hosts:
    static:
      - ${HERD_HOST_IP}:15004

origin:
  hosts:
    static:
      - ${HERD_HOST_IP}:15002

remotes: {}

tag_replication:
  retry_interval: 100ms
  poll_retries_interval: 250ms

tag_types:
  - namespace: .*
    type: docker
    root: tags

tag_store:
  write_through: false

writeback:
  retry_interval: 100ms
  poll_retries_interval: 250ms

nginx:
  cache_dir: /tmp/kraken-build-index-nginx/

tls:
  name: kraken
  server:
    disabled: true
  client:
    disabled: true
