extends: base.yaml

peerstore:
  redis:
    redis_cluster:
      addrs:
        - "${CLUSTER_NODE_1}:${REDIS_PORT}"
        - "${CLUSTER_NODE_2}:${REDIS_PORT}"
        - "${CLUSTER_NODE_3}:${REDIS_PORT}"
      max_redirects: 3

origin:
  hosts:
    static:
      - "${CLUSTER_NODE_1}:${ORIGIN_PORT}"
      - "${CLUSTER_NODE_2}:${ORIGIN_PORT}"
      - "${CLUSTER_NODE_3}:${ORIGIN_PORT}"

trackerserver:
  announce_interval: 3s

nginx:
  cache_dir: /tmp/kraken-tracker-nginx/

tls:
  name: kraken
  server:
    disabled: true
  client:
    disabled: true
